### ISSUE TITLE
Compiled good but app crash

### ISSUE THREAD

**Issue by wladek1909** [kivy-garden/zbarcam#27]
Hi my problem is. Im compile from you buildozer.spec. Compiling have no error, but
when i start app in my device, app crash.

This is log file: logcat 
please help!!!
```
--------- beginning of main
--------- beginning of system
01-25 15:55:28.560 31372 31393 I python  : Initializing Python for Android
01-25 15:55:28.560 31372 31393 I python  : Setting additional env vars from p4a_
env_vars.txt
01-25 15:55:28.560 31372 31393 I python  : Changing directory to the one provide
d by ANDROID_ARGUMENT
01-25 15:55:28.560 31372 31393 I python  : /data/user/0/com.soft.amour.dkcam/fil
es/app
01-25 15:55:28.560 31372 31393 I python  : Preparing to initialize python
01-25 15:55:28.560 31372 31393 I python  : _python_bundle dir exists
01-25 15:55:28.560 31372 31393 I python  : calculated paths to be...
01-25 15:55:28.560 31372 31393 I python  : /data/user/0/com.soft.amour.dkcam/fil
es/app/_python_bundle/stdlib.zip:/data/user/0/com.soft.amour.dkcam/files/app/_py
thon_bundle/modules
01-25 15:55:28.561 31372 31393 I python  : set wchar paths...
01-25 15:55:28.727 31372 31393 I python  : Initialized python
01-25 15:55:28.727 31372 31393 I python  : AND: Init threads
01-25 15:55:28.730 31372 31393 I python  : testing python print redirection
01-25 15:55:28.734 31372 31393 I python  : Android path ['.', '/data/user/0/com.
soft.amour.dkcam/files/app/_python_bundle/stdlib.zip', '/data/user/0/com.soft.am
our.dkcam/files/app/_python_bundle/modules', '/data/user/0/com.soft.amour.dkcam/
files/app/_python_bundle/site-packages']
01-25 15:55:28.736 31372 31393 I python  : os.environ is environ({'PATH': '/sbin
:/vendor/bin:/system/sbin:/system/bin:/system/xbin', 'ANDROID_BOOTLOGO': '1', 'A
NDROID_ROOT': '/system', 'ANDROID_ASSETS': '/system/app', 'ANDROID_DATA': '/data
', 'ANDROID_STORAGE': '/storage', 'EXTERNAL_STORAGE': '/sdcard', 'ASEC_MOUNTPOIN
T': '/mnt/asec', 'BOOTCLASSPATH': '/system/framework/core-oj.jar:/system/framewo
rk/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:
/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/fram
ework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common
.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/
framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar:/syst
em/framework/mediatek-common.jar:/system/framework/mediatek-framework.jar:/syste
m/framework/mediatek-telephony-common.jar', 'SYSTEMSERVERCLASSPATH': '/system/fr
amework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wi
fi-service.jar', 'ANDROID_SOCKET_zygote': '9', 'ANDROID_ENTRYPOINT': 'main.pyc',
 'ANDROID_ARGUMENT': '/data/user/0/com.soft.amour.dkcam/files/app', 'ANDROID_APP
_PATH': '/data/user/0/com.soft.amour.dkcam/files/app', 'ANDROID_PRIVATE': '/data
/user/0/com.soft.amour.dkcam/files', 'ANDROID_UNPACK': '/data/user/0/com.soft.am
our.dkcam/files/app', 'PYTHONHOME': '/data/user/0/com.soft.amour.dkcam/files/app
', 'PYTHONPATH': '/data/user/0/com.soft.amour.dkcam/files/app:/data/user/0/com.s
oft.amour.dkcam/files/app/lib', 'PYTHONOPTIMIZE': '2', 'P4A_BOOTSTRAP': 'SDL2',
'PYTHON_NAME': 'python', 'P4A_IS_WINDOWED': 'True', 'P4A_ORIENTATION': 'portrait
', 'P4A_NUMERIC_VERSION': 'None', 'P4A_MINSDK': '21', 'LC_CTYPE': 'C.UTF-8'})
01-25 15:55:28.736 31372 31393 I python  : Android kivy bootstrap done. __name__
 is __main__
01-25 15:55:28.736 31372 31393 I python  : AND: Ran string
01-25 15:55:28.736 31372 31393 I python  : Run user program, change dir and exec
ute entrypoint
01-25 15:55:29.190 31372 31393 I python  : [INFO   ] [Logger      ] Record log i
n /data/user/0/com.soft.amour.dkcam/files/app/.kivy/logs/kivy_20-01-25_3.txt
01-25 15:55:29.191 31372 31393 I python  : [INFO   ] [Kivy        ] v1.11.1
01-25 15:55:29.192 31372 31393 I python  : [INFO   ] [Kivy        ] Installed at
 "/data/user/0/com.soft.amour.dkcam/files/app/_python_bundle/site-packages/kivy/
__init__.pyc"
01-25 15:55:29.194 31372 31393 I python  : [INFO   ] [Python      ] v3.7.1 (defa
ult, Jan 25 2020, 14:18:09)
01-25 15:55:29.194 31372 31393 I python  : [Clang 8.0.2 (https://android.googles
ource.com/toolchain/clang 40173bab62ec7462
01-25 15:55:29.195 31372 31393 I python  : [INFO   ] [Python      ] Interpreter
at "android_python"
01-25 15:55:31.767 31372 31393 I python  : [INFO   ] [Factory     ] 184 symbols
loaded
01-25 15:55:32.982 31372 31393 I python  : [INFO   ] [Image       ] Providers: i
mg_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
01-25 15:55:33.105 31372 31393 I python  : [ERROR  ]
01-25 15:55:33.105 31372 31393 I python  : Traceback (most recent call last):
01-25 15:55:33.105 31372 31393 I python  :   File "/home/kivy/Desktop/New/.build
ozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/pa
rser.py", line 471, in execute_directives
01-25 15:55:33.105 31372 31393 I python  : ModuleNotFoundError: No module named
'kivy_garden.zbarcam'
01-25 15:55:33.105 31372 31393 I python  :
01-25 15:55:33.105 31372 31393 I python  : During handling of the above exceptio
n, another exception occurred:
01-25 15:55:33.105 31372 31393 I python  :
01-25 15:55:33.105 31372 31393 I python  : Traceback (most recent call last):
01-25 15:55:33.105 31372 31393 I python  :   File "/home/kivy/Desktop/New/.build
ozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/pa
rser.py", line 473, in execute_directives
01-25 15:55:33.105 31372 31393 I python  : ModuleNotFoundError: No module named
'kivy_garden.zbarcam'
01-25 15:55:33.106 31372 31393 I python  :  Traceback (most recent call last):
01-25 15:55:33.108 31372 31393 I python  :    File "/home/kivy/Desktop/New/.buil
dozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/p
arser.py", line 471, in execute_directives
01-25 15:55:33.110 31372 31393 I python  :  ModuleNotFoundError: No module named
 'kivy_garden.zbarcam'
01-25 15:55:33.111 31372 31393 I python  :
01-25 15:55:33.112 31372 31393 I python  :  During handling of the above excepti
on, another exception occurred:
01-25 15:55:33.112 31372 31393 I python  :
01-25 15:55:33.113 31372 31393 I python  :  Traceback (most recent call last):
01-25 15:55:33.115 31372 31393 I python  :    File "/home/kivy/Desktop/New/.buil
dozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/p
arser.py", line 473, in execute_directives
01-25 15:55:33.117 31372 31393 I python  :  ModuleNotFoundError: No module named
 'kivy_garden.zbarcam'
01-25 15:55:33.118 31372 31393 I python  :
01-25 15:55:33.119 31372 31393 I python  :  During handling of the above excepti
on, another exception occurred:
01-25 15:55:33.120 31372 31393 I python  :
01-25 15:55:33.121 31372 31393 I python  :  Traceback (most recent call last):
01-25 15:55:33.122 31372 31393 I python  :    File "/home/kivy/Desktop/New/.buil
dozer/android/app/main.py", line 42, in <module>
01-25 15:55:33.123 31372 31393 I python  :    File "/home/kivy/Desktop/New/.buil
dozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/b
uilder.py", line 368, in load_string
01-25 15:55:33.125 31372 31393 I python  :    File "/home/kivy/Desktop/New/.buil
dozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/p
arser.py", line 401, in __init__
01-25 15:55:33.127 31372 31393 I python  :    File "/home/kivy/Desktop/New/.buil
dozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/p
arser.py", line 507, in parse
01-25 15:55:33.129 31372 31393 I python  :    File "/home/kivy/Desktop/New/.buil
dozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/p
arser.py", line 484, in execute_directives
01-25 15:55:33.131 31372 31393 I python  :  kivy.lang.parser.ParserException: Pa
rser: File "<inline>", line 3:
01-25 15:55:33.131 31372 31393 I python  :  ...
01-25 15:55:33.132 31372 31393 I python  :        1:
01-25 15:55:33.133 31372 31393 I python  :        2:<MenuScreen>:
01-25 15:55:33.134 31372 31393 I python  :  >>    3:#:import ZBarCam kivy_garden
.zbarcam.ZBarCam
01-25 15:55:33.135 31372 31393 I python  :        4:#:import ZBarSymbol pyzbar.p
yzbar.ZBarSymbol
01-25 15:55:33.136 31372 31393 I python  :        5:
01-25 15:55:33.137 31372 31393 I python  :  ...
01-25 15:55:33.138 31372 31393 I python  :  Unable to import package 'kivy_garde
n.zbarcam.ZBarCam'
01-25 15:55:33.139 31372 31393 I python  : Python for android ended.
```

**Comment by wladek1909** [comment]
Ok i fix this error, added source to my project. but i have new error!
```
01-26 17:47:02.724 22809 22830 I python  :  Traceback (most recent call last):
01-26 17:47:02.725 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/builder.py", line 700, in _apply_rule
01-26 17:47:02.727 22809 22830 I python  :    File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
01-26 17:47:02.729 22809 22830 I python  :    File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
01-26 17:47:02.731 22809 22830 I python  :    File "kivy/properties.pyx", line 839, in kivy.properties.ListProperty.set
01-26 17:47:02.733 22809 22830 I python  :    File "kivy/properties.pyx", line 544, in kivy.properties.Property.set
01-26 17:47:02.734 22809 22830 I python  :    File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
01-26 17:47:02.736 22809 22830 I python  :    File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
01-26 17:47:02.738 22809 22830 I python  :    File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
01-26 17:47:02.739 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy_garden/xcamera/xcamera.py", line 85, in _on_index
01-26 17:47:02.741 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy_garden/xcamera/xcamera.py", line 88, in _on_index_dispatch
01-26 17:47:02.742 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/uix/camera.py", line 103, in _on_index
01-26 17:47:02.744 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/core/camera/camera_android.py", line 42, in __init__
01-26 17:47:02.746 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/core/camera/__init__.py", line 70, in __init__
01-26 17:47:02.748 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/core/camera/camera_android.py", line 54, in init_camera
01-26 17:47:02.750 22809 22830 I python  :    File "jnius/jnius_export_class.pxi", line 769, in jnius.jnius.JavaMethod.__call__
01-26 17:47:02.752 22809 22830 I python  :    File "jnius/jnius_export_class.pxi", line 863, in jnius.jnius.JavaMethod.call_method
01-26 17:47:02.753 22809 22830 I python  :    File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
01-26 17:47:02.755 22809 22830 I python  :  jnius.jnius.JavaException: JVM exception occurred: setParameters failed
01-26 17:47:02.756 22809 22830 I python  :
01-26 17:47:02.757 22809 22830 I python  :  During handling of the above exception, another exception occurred:
01-26 17:47:02.758 22809 22830 I python  :
01-26 17:47:02.759 22809 22830 I python  :  Traceback (most recent call last):
01-26 17:47:02.759 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/app/main.py", line 67, in <module>
01-26 17:47:02.761 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/uix/relativelayout.py", line 265, in __init__
01-26 17:47:02.763 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/uix/floatlayout.py", line 65, in __init__
01-26 17:47:02.765 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/uix/layout.py", line 76, in __init__
01-26 17:47:02.767 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/uix/widget.py", line 361, in __init__
01-26 17:47:02.769 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/uix/widget.py", line 469, in apply_class_lang_rules
01-26 17:47:02.771 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/builder.py", line 538, in apply
01-26 17:47:02.772 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/builder.py", line 659, in _apply_rule
01-26 17:47:02.774 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/builder.py", line 657, in _apply_rule
01-26 17:47:02.776 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/uix/widget.py", line 469, in apply_class_lang_rules
01-26 17:47:02.777 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/builder.py", line 538, in apply
01-26 17:47:02.779 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/builder.py", line 659, in _apply_rule
01-26 17:47:02.781 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/builder.py", line 657, in _apply_rule
01-26 17:47:02.782 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/uix/widget.py", line 469, in apply_class_lang_rules
01-26 17:47:02.784 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/builder.py", line 538, in apply
01-26 17:47:02.786 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/builder.py", line 707, in _apply_rule
01-26 17:47:02.788 22809 22830 I python  :  kivy.lang.builder.BuilderException: Parser: File "/data/user/0/com.soft.amour.dkcam/files/app/_python_bundle/site-packages/kivy_garden/xcamera/xcamera.kv", line 27:
01-26 17:47:02.789 22809 22830 I python  :  ...
01-26 17:47:02.790 22809 22830 I python  :       25:
01-26 17:47:02.790 22809 22830 I python  :       26:    id: camera
01-26 17:47:02.791 22809 22830 I python  :  >>   27:    resolution: 640, 480 # 1920, 1080
01-26 17:47:02.792 22809 22830 I python  :       28:    allow_stretch: True
01-26 17:47:02.793 22809 22830 I python  :       29:
01-26 17:47:02.794 22809 22830 I python  :  ...
01-26 17:47:02.794 22809 22830 I python  :  JavaException: JVM exception occurred: setParameters failed
01-26 17:47:02.795 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/lang/builder.py", line 700, in _apply_rule
01-26 17:47:02.796 22809 22830 I python  :    File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
01-26 17:47:02.797 22809 22830 I python  :    File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
01-26 17:47:02.798 22809 22830 I python  :    File "kivy/properties.pyx", line 839, in kivy.properties.ListProperty.set
01-26 17:47:02.799 22809 22830 I python  :    File "kivy/properties.pyx", line 544, in kivy.properties.Property.set
01-26 17:47:02.799 22809 22830 I python  :    File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
01-26 17:47:02.800 22809 22830 I python  :    File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
01-26 17:47:02.801 22809 22830 I python  :    File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
01-26 17:47:02.802 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy_garden/xcamera/xcamera.py", line 85, in _on_index
01-26 17:47:02.803 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy_garden/xcamera/xcamera.py", line 88, in _on_index_dispatch
01-26 17:47:02.803 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/uix/camera.py", line 103, in _on_index
01-26 17:47:02.804 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/core/camera/camera_android.py", line 42, in __init__
01-26 17:47:02.805 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/core/camera/__init__.py", line 70, in __init__
01-26 17:47:02.806 22809 22830 I python  :    File "/home/kivy/Desktop/N/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/dkcam/kivy/core/camera/camera_android.py", line 54, in init_camera
01-26 17:47:02.807 22809 22830 I python  :    File "jnius/jnius_export_class.pxi", line 769, in jnius.jnius.JavaMethod.__call__
01-26 17:47:02.808 22809 22830 I python  :    File "jnius/jnius_export_class.pxi", line 863, in jnius.jnius.JavaMethod.call_method
01-26 17:47:02.809 22809 22830 I python  :    File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
01-26 17:47:02.810 22809 22830 I python  :
01-26 17:47:02.810 22809 22830 I python  : Python for android ended.
```

**Comment by AndreMiras** [comment]
This is often because you need to give camera permission.
Think about using triple back tick when posting to make the log more readable. I've updated your comments.
Also please share minimal reproduction code as well as the `buildozer.spec` file so we can help

**Comment by ahmed-asn** [comment]
which source do you added?

**Comment by ahmed-asn** [comment]
i have the same problem like the first problem from @wladek1909 and i dont know which source he added can somebody help me??

**Comment by ahmed-asn** [comment]
@AndreMiras

**Comment by abhishekju06** [comment]
My understanding is that when you encounter the error kivy_garden.zbarcam you need to change it to 
kivy.garden.zbarcam
garden install zbarcam --upgrade would help.
This is on your machine but for buildozer I think zbarcam command similar to #:import XCamera kivy_garden.xcamera.XCamera would compile.

About the below code:
26:    id: camera
01-26 17:47:02.791 22809 22830 I python  :  >>   27:    resolution: 640, 480 # 1920, 1080
01-26 17:47:02.792 22809 22830 I python  :       28:    allow_stretch: True

This is not using Zbarcam rather its using the Camera program for Kivy which has got lot of issues with buildozer 
@AndreMiras could you please correct me if I am wrong?

**Comment by AndreMiras** [comment]
I think the `kivy_garden.zbarcam` is fine actually. Also this module should NOT be installed with `garden install` command as this is deprecated. On desktop it needs to be installed with `pip install zbarcam` as stated in the README.md. And in the same fashion for Android you need the `zbarcam` in the `requirements` list of the `buildozer.spec`. Last is you need the `android.permissions = CAMERA`.

**Comment by abhishekju06** [comment]
@AndreMiras  I want to store the images captured by XCAMERA in /storage/emulated/0/my_folder. How would I do it?

My code snippet:

<ProfileScreen>:
    name: 'profile'
    FloatLayout:
        orientation: 'vertical'
        XCamera:
            id: xcamera
            on_picture_taken: root.picture_taken(*args)

class ProfileScreen(Screen):
        def picture_taken(self, *args):
                  pass

**Comment by hetishah** [comment]
@AndreMiras I have the error. Unable to import package kivy_garden.xcamera.XCamera. Please tell me how to resolve this error?

**Comment by mguinhos** [comment]
Also having this problem

**Comment by xavierfiechter** [comment]
Also having issues with the camera / qr scanner.
