### ISSUE TITLE
compiled properly but when using kivy app it crashes...

### ISSUE THREAD

**Issue by sai3910** [kivy-garden/zbarcam#34]
```
06-19 17:06:30.673 22795 22970 I python  : Android kivy bootstrap done. __name__ is __main__
06-19 17:06:30.673 22795 22970 I python  : AND: Ran string
06-19 17:06:30.673 22795 22970 I python  : Run user program, change dir and execute entrypoint
06-19 17:06:30.768 22795 22970 I python  : [WARNING] [Config      ] Older configuration version detected (0 instead of 21)
06-19 17:06:30.770 22795 22970 I python  : [WARNING] [Config      ] Upgrading configuration in progress.
06-19 17:06:30.774 22795 22970 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.autopeepal.timesqr/files/app/.kivy/logs/kivy_20-06-19_0.txt
06-19 17:06:30.774 22795 22970 I python  : [INFO   ] [Kivy        ] v1.11.1
06-19 17:06:30.774 22795 22970 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/org.autopeepal.timesqr/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
06-19 17:06:30.774 22795 22970 I python  : [INFO   ] [Python      ] v3.8.1 (default, Jun 19 2020, 14:57:02) 
06-19 17:06:30.774 22795 22970 I python  : [Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
06-19 17:06:30.774 22795 22970 I python  : [INFO   ] [Python      ] Interpreter at ""
06-19 17:06:31.409 22795 22970 I python  : [INFO   ] [Factory     ] 184 symbols loaded
06-19 17:06:31.655 22795 22970 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
06-19 17:06:31.688 22795 22970 I python  : [INFO   ] [Text        ] Provider: sdl2
06-19 17:06:31.715 22795 22970 I python  : [INFO   ] [Window      ] Provider: sdl2
06-19 17:06:31.740 22795 22970 I python  : [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
06-19 17:06:31.741 22795 22970 I python  : [INFO   ] [GL          ] Backend used <sdl2>
06-19 17:06:31.741 22795 22970 I python  : [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 V@415.0 (GIT@e4029f9, I6b4cbc7431, 1569964966) (Date:10/01/19)'>
06-19 17:06:31.741 22795 22970 I python  : [INFO   ] [GL          ] OpenGL vendor <b'Qualcomm'>
06-19 17:06:31.742 22795 22970 I python  : [INFO   ] [GL          ] OpenGL renderer <b'Adreno (TM) 616'>
06-19 17:06:31.742 22795 22970 I python  : [INFO   ] [GL          ] OpenGL parsed version: 3, 2
06-19 17:06:31.742 22795 22970 I python  : [INFO   ] [GL          ] Texture max size <16384>
06-19 17:06:31.742 22795 22970 I python  : [INFO   ] [GL          ] Texture max units <16>
06-19 17:06:31.774 22795 22970 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
06-19 17:06:31.774 22795 22970 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
06-19 17:06:31.964 22795 22970 I python  : [INFO   ] [KivyMD      ] KivyMD version: 0.100.2
06-19 17:06:32.231 22795 22970 I python  : [INFO   ] [GL          ] NPOT texture support is available
06-19 17:06:33.425 22795 22970 I python  : [WARNING] [Base        ] Unknown <android> provider
06-19 17:06:33.426 22795 22970 I python  : [INFO   ] [Base        ] Start application main loop
06-19 17:06:33.445 22795 22970 I python  : [ERROR  ] 
06-19 17:06:33.445 22795 22970 I python  : Traceback (most recent call last):
06-19 17:06:33.445 22795 22970 I python  :   File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/lang/parser.py", line 471, in execute_directives
06-19 17:06:33.445 22795 22970 I python  : ModuleNotFoundError: No module named 'kivy_garden.xcamera'
06-19 17:06:33.445 22795 22970 I python  : 
06-19 17:06:33.445 22795 22970 I python  : During handling of the above exception, another exception occurred:
06-19 17:06:33.445 22795 22970 I python  : 
06-19 17:06:33.445 22795 22970 I python  : Traceback (most recent call last):
06-19 17:06:33.445 22795 22970 I python  :   File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/lang/parser.py", line 473, in execute_directives
06-19 17:06:33.445 22795 22970 I python  : ModuleNotFoundError: No module named 'kivy_garden.xcamera'
06-19 17:06:33.445 22795 22970 I python  : [INFO   ] [Base        ] Leaving application in progress...
06-19 17:06:33.446 22795 22970 I python  :  Traceback (most recent call last):
06-19 17:06:33.446 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/lang/parser.py", line 471, in execute_directives
06-19 17:06:33.447 22795 22970 I python  :  ModuleNotFoundError: No module named 'kivy_garden.xcamera'
06-19 17:06:33.447 22795 22970 I python  :  
06-19 17:06:33.447 22795 22970 I python  :  During handling of the above exception, another exception occurred:
06-19 17:06:33.447 22795 22970 I python  :  
06-19 17:06:33.447 22795 22970 I python  :  Traceback (most recent call last):
06-19 17:06:33.448 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/lang/parser.py", line 473, in execute_directives
06-19 17:06:33.448 22795 22970 I python  :  ModuleNotFoundError: No module named 'kivy_garden.xcamera'
06-19 17:06:33.448 22795 22970 I python  :  
06-19 17:06:33.448 22795 22970 I python  :  During handling of the above exception, another exception occurred:
06-19 17:06:33.449 22795 22970 I python  :  
06-19 17:06:33.449 22795 22970 I python  :  Traceback (most recent call last):
06-19 17:06:33.449 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/app/main.py", line 537, in <module>
06-19 17:06:33.449 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/app.py", line 855, in run
06-19 17:06:33.450 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/base.py", line 504, in runTouchApp
06-19 17:06:33.450 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/core/window/window_sdl2.py", line 747, in mainloop
06-19 17:06:33.450 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/core/window/window_sdl2.py", line 479, in _mainloop
06-19 17:06:33.451 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/base.py", line 339, in idle
06-19 17:06:33.451 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/clock.py", line 591, in tick
06-19 17:06:33.451 22795 22970 I python  :    File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
06-19 17:06:33.452 22795 22970 I python  :    File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
06-19 17:06:33.452 22795 22970 I python  :    File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
06-19 17:06:33.452 22795 22970 I python  :    File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
06-19 17:06:33.453 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/app/main.py", line 98, in loading_app
06-19 17:06:33.453 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/app/budscreens/loginScreen.py", line 33, in __init__
06-19 17:06:33.453 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/uix/relativelayout.py", line 265, in __init__
06-19 17:06:33.454 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/uix/floatlayout.py", line 65, in __init__
06-19 17:06:33.454 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/uix/layout.py", line 76, in __init__
06-19 17:06:33.454 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/uix/widget.py", line 359, in __init__
06-19 17:06:33.455 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/uix/widget.py", line 467, in apply_class_lang_rules
06-19 17:06:33.455 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/lang/builder.py", line 536, in apply
06-19 17:06:33.456 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/lang/builder.py", line 658, in _apply_rule
06-19 17:06:33.456 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/lang/builder.py", line 654, in _apply_rule
06-19 17:06:33.456 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy_garden/zbarcam/zbarcam.py", line 31, in __init__
06-19 17:06:33.457 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/lang/builder.py", line 301, in load_file
06-19 17:06:33.457 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/lang/builder.py", line 368, in load_string
06-19 17:06:33.459 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/lang/parser.py", line 401, in __init__
06-19 17:06:33.459 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/lang/parser.py", line 507, in parse
06-19 17:06:33.459 22795 22970 I python  :    File "/home/sai/kivy_projects/timesqr/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/timesqr/kivy/lang/parser.py", line 482, in execute_directives
06-19 17:06:33.460 22795 22970 I python  :  kivy.lang.parser.ParserException: Parser: File "/data/data/org.autopeepal.timesqr/files/app/_python_bundle/site-packages/kivy_garden/zbarcam/zbarcam.kv", line 1:
06-19 17:06:33.460 22795 22970 I python  :  ...
06-19 17:06:33.460 22795 22970 I python  :  >>    1:#:import XCamera kivy_garden.xcamera.XCamera
06-19 17:06:33.460 22795 22970 I python  :        2:#:import is_android kivy_garden.zbarcam.utils.is_android
06-19 17:06:33.461 22795 22970 I python  :        3:<ZBarCam>:
06-19 17:06:33.461 22795 22970 I python  :  ...
06-19 17:06:33.461 22795 22970 I python  :  Unable to import package 'kivy_garden.xcamera.XCamera'
06-19 17:06:33.461 22795 22970 I python  : Python for android ended.

```
**Buildozer.spec**
```


requirements = python3,kivy==1.11.1,pyzbar,libzbar,Pillow,chardet,idna,zbarcam,kivy_garden

android.permissions=CAMERA
```

**Comment by AndreMiras** [comment]
I would say, don't use `kivy_garden` in your requirements to begin and next you need to add `xcamera` to your dependencies.
This is documented here https://github.com/kivy-garden/zbarcam/blob/2020.0524/buildozer.spec#L48
If you need support feel free to ask on Discord. And if you think it's still a bug (and not a support question) feel free to re-open or provide a bugfix

**Comment by sai3910** [comment]
still this error exists
**buildozer.spec**
```requirements = python3,kivy==1.11.1,pyzbar==0.1.8,Pillow,chardet,idna,zbarcam,xcamera==2019.928```

log
```
06-19 21:10:04.217 12068 12136 I python  :  ...
06-19 21:10:04.217 12068 12136 I python  :  >>    1:#:import XCamera kivy_garden.xcamera.XCamera
06-19 21:10:04.217 12068 12136 I python  :        2:#:import is_android kivy_garden.zbarcam.utils.is_android
06-19 21:10:04.218 12068 12136 I python  :        3:<ZBarCam>:
06-19 21:10:04.218 12068 12136 I python  :  ...
06-19 21:10:04.218 12068 12136 I python  :  Unable to import package 'kivy_garden.xcamera.XCamera'
06-19 21:10:04.218 12068 12136 I python  : Python for android ended.
```

**Comment by AndreMiras** [comment]
Yeah I assume you need to build from scratch, like clean build. Let's talk on Discord

**Comment by BernardinD** [comment]
Was there a verified solution for this? I'm having a similar problem

**Comment by wanaxe** [comment]
I have the exact same problem. Adding `Kivy-Garden` to the `requirements` , fixes it.

That dependency is included in the `requirements/requirements-base.txt`, but missing in the `buildozer.spec` (not updated?!).
