### ISSUE TITLE
Unable to import package 'kivy_garden.zbarcam.ZBarCam'

### ISSUE THREAD

**Issue by richierh** [kivy-garden/zbarcam#56]
Why this happened ?

```
Traceback (most recent call last):
01-20 16:40:09.234  3132  3152 I python  :    File "/github/workspace/.buildozer/android/platform/build-x86/build/python-installs/myapp/kivy/lang/parser.py", line 473, in execute_directives
01-20 16:40:09.234  3132  3152 I python  :  ModuleNotFoundError: No module named 'kivy_garden.zbarcam'
01-20 16:40:09.235  3132  3152 I python  :  
01-20 16:40:09.235  3132  3152 I python  :  During handling of the above exception, another exception occurred:
01-20 16:40:09.235  3132  3152 I python  :  
01-20 16:40:09.235  3132  3152 I python  :  Traceback (most recent call last):
01-20 16:40:09.235  3132  3152 I python  :    File "/github/workspace/.buildozer/android/app/main.py", line 48, in <module>
01-20 16:40:09.236  3132  3152 I python  :    File "/github/workspace/.buildozer/android/platform/build-x86/build/python-installs/myapp/kivy/app.py", line 828, in run
01-20 16:40:09.236  3132  3152 I python  :    File "/github/workspace/.buildozer/android/platform/build-x86/build/python-installs/myapp/kivy/app.py", line 599, in load_kv
01-20 16:40:09.237  3132  3152 I python  :    File "/github/workspace/.buildozer/android/platform/build-x86/build/python-installs/myapp/kivy/lang/builder.py", line 301, in load_file
01-20 16:40:09.237  3132  3152 I python  :    File "/github/workspace/.buildozer/android/platform/build-x86/build/python-installs/myapp/kivy/lang/builder.py", line 368, in load_string
01-20 16:40:09.238  3132  3152 I python  :    File "/github/workspace/.buildozer/android/platform/build-x86/build/python-installs/myapp/kivy/lang/parser.py", line 401, in __init__
01-20 16:40:09.238  3132  3152 I python  :    File "/github/workspace/.buildozer/android/platform/build-x86/build/python-installs/myapp/kivy/lang/parser.py", line 507, in parse
01-20 16:40:09.239  3132  3152 I python  :    File "/github/workspace/.buildozer/android/platform/build-x86/build/python-installs/myapp/kivy/lang/parser.py", line 482, in execute_directives
01-20 16:40:09.240  3132  3152 I python  :  kivy.lang.parser.ParserException: Parser: File "/data/data/org.test.myapp/files/app/demo.kv", line 1:
01-20 16:40:09.241  3132  3152 I python  :  ...
01-20 16:40:09.241  3132  3152 I python  :  >>    1:#:import ZBarCam kivy_garden.zbarcam.ZBarCam
01-20 16:40:09.241  3132  3152 I python  :        2:#:import ZBarSymbol pyzbar.pyzbar.ZBarSymbol
01-20 16:40:09.241  3132  3152 I python  :        3:#:import QRCodeWidget kivy_garden.qrcode
01-20 16:40:09.242  3132  3152 I python  :  ...
01-20 16:40:09.242  3132  3152 I python  :  Unable to import package 'kivy_garden.zbarcam.ZBarCam'
01-20 16:40:09.242  3132  3152 I python  : Python for android ended.

```

**Comment by mintminttea** [comment]
copy kivy_garden folder inside scr to your app main folder should do the trick

**Comment by kompish** [comment]
> copy kivy_garden folder inside scr to your app main folder should do the trick

can you explain better because i try to copy kivy_garden folder inside folder of my main.py but still getting the same error.

**Comment by mguinhos** [comment]
Also having this problem
