### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_state'

### ISSUE THREAD

**Issue by petaflot** [kivy-garden/zbarcam#61]
trying to read some codes on my desktop with logitech USB webcam. gucview displays an image as expected.

zbarcam says

```
[INFO   ] [CameraGi    ] Using Gstreamer 1.16.3.0
[INFO   ] [Camera      ] Provider: gi(['camera_picamera'] ignored)
...
   File "/home/meta/.local/lib/python3.9/site-packages/kivy/core/camera/__init__.py", line 70, in __init__
     self.init_camera()
   File "/home/meta/.local/lib/python3.9/site-packages/kivy/core/camera/camera_gi.py", line 89, in init_camera
     self._pipeline = Gst.parse_launch(pl.format(video_src, caps))
 gi.repository.GLib.Error: gst_parse_error: no element "v4l2src" (1)
 Error in atexit._run_exitfuncs:
 Traceback (most recent call last):
   File "/home/meta/.local/lib/python3.9/site-packages/kivy/core/camera/camera_gi.py", line 169, in camera_gi_clean
     camera.stop()
   File "/home/meta/.local/lib/python3.9/site-packages/kivy/core/camera/camera_gi.py", line 123, in stop
     self._pipeline.set_state(Gst.State.PAUSED)
 AttributeError: 'NoneType' object has no attribute 'set_state'
```

this was obtained with src/main.py

a question (maybe related?) comes to my mind: how to do camera selection?

**Comment by petaflot** [comment]
was missing a package on my system :-s
